# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('fico', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='DocTypeAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('docType', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='DTIAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('dti', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='GradeAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='IOAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('io', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='LoanBalanceAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('balance', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTermAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('loanTerm', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('occupancy', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PrepayAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('prepayTerm', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypeAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('propertyType', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ReservesAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('reserves', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='StateAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateSheetName', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('adj', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
