# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0003_auto_20170409_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantermadj',
            name='ltv',
        ),
    ]
