# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0004_remove_loantermadj_ltv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fico', models.CharField(max_length=128)),
                ('ltv', models.CharField(max_length=128)),
                ('citizenship', models.CharField(max_length=128)),
                ('doctype', models.CharField(max_length=128)),
                ('dti', models.CharField(max_length=128)),
                ('loanamount', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('occupancy', models.CharField(max_length=128)),
                ('propType', models.CharField(max_length=128)),
                ('io', models.CharField(max_length=128)),
                ('term', models.CharField(max_length=128)),
                ('prepay', models.CharField(max_length=128)),
                ('reserves', models.CharField(max_length=128)),
                ('x30x12', models.IntegerField()),
                ('x60x12', models.IntegerField()),
                ('x90x12', models.IntegerField()),
                ('x30x24', models.IntegerField()),
                ('x60x24', models.IntegerField()),
                ('x90x24', models.IntegerField()),
                ('monthsFC', models.IntegerField()),
                ('monthsSS', models.IntegerField()),
                ('monthsDIL', models.IntegerField()),
                ('monthsBK', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=6)),
                ('eligibility', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='loantermadj',
            name='ltv',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
