# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0006_remove_loantermadj_ltv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricer',
            name='monthsBK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricer',
            name='monthsDIL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricer',
            name='monthsFC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricer',
            name='monthsSS',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
