# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0007_auto_20170414_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricer',
            name='bkChapter',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctypeadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dtiadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='gradeadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ioadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanbalanceadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loantermadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='occupancyadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prepayadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='propertytypeadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purposeadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reservesadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stateadj',
            name='adj',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=6),
        ),
    ]
