# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0009_auto_20170421_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricer',
            name='dscr',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricer',
            name='fthbflag',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricer',
            name='seflag',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
