# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricer', '0010_auto_20170424_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAProductMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('fico', models.CharField(max_length=128)),
                ('loanamount', models.CharField(max_length=128)),
                ('docType', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('maxLTV', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DTIProductMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('fico', models.CharField(max_length=128)),
                ('loanamount', models.CharField(max_length=128)),
                ('maxLTV', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FNProductMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.CharField(max_length=128)),
                ('docType', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=128)),
                ('fico', models.CharField(max_length=128)),
                ('loanamount', models.CharField(max_length=128)),
                ('maxLTV', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PIProductMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.CharField(max_length=128)),
                ('fico', models.CharField(max_length=128)),
                ('loanamount', models.CharField(max_length=128)),
                ('reserves', models.CharField(max_length=128)),
                ('purpose', models.CharField(max_length=128)),
                ('maxLTV', models.CharField(max_length=128)),
            ],
        ),
    ]
